name: swiftlint

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7

      - run: bin/lint
